//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.8669
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketPlan.WebService
{
    using System;
    using System.Collections.Generic;
    using Edsa.Data;
    using Edsa.Data.Attributes;
    
    
    [Serializable()]
    [DbTable(Name="HouseConstructionMaterials", DatabaseType=DatabaseType.SqlServer, ConnectionSettingKeyName="SocketPlan.WebService.Properties.Settings.ConnectionStringOfFlagSetting")]
    public partial class HouseConstructionMaterial : DataEntity<HouseConstructionMaterial>
    {
        
        private string _ConstructionCode;
        
        private string _ConstructionMaterialCode;
        
        private int _ConstructionMaterialDetailCode;
        
        private int _Floor;
        
        private int _SequenceNo;
        
        private string _ProductCode;
        
        private System.Nullable<decimal> _Quantity;
        
        // 1：HRD 2：日本
        private int _SupplierLocality;
        
        private System.Nullable<int> _WoodKindCode;
        
        private string _SizeName;
        
        // 1：防腐あり
        private bool _UsedPreservativeTreatment;
        
        private System.Nullable<System.DateTime> _StartedProductionDate;
        
        private System.Nullable<System.DateTime> _FinishedProcessDate;
        
        private System.Nullable<System.DateTime> _FinishedPreservativeTreatmentDate;
        
        private int _Package;
        
        private string _ShippingWarehouseCode;
        
        private string _Remarks;
        
        // 1：不可
        private bool _Uneditable;
        
        private System.Nullable<System.DateTime> _UpdatedDate;
        
        [DbColumn(Name="ConstructionCode", TypeName="varchar", IsPrimaryKey=true, Length=12)]
        public virtual string ConstructionCode
        {
            get
            {
                return this._ConstructionCode;
            }
            set
            {
                this._ConstructionCode = value;
            }
        }
        
        [DbColumn(Name="ConstructionMaterialCode", TypeName="varchar", IsPrimaryKey=true, Length=2)]
        public virtual string ConstructionMaterialCode
        {
            get
            {
                return this._ConstructionMaterialCode;
            }
            set
            {
                this._ConstructionMaterialCode = value;
            }
        }
        
        [DbColumn(Name="ConstructionMaterialDetailCode", TypeName="int", IsPrimaryKey=true, Length=4)]
        public virtual int ConstructionMaterialDetailCode
        {
            get
            {
                return this._ConstructionMaterialDetailCode;
            }
            set
            {
                this._ConstructionMaterialDetailCode = value;
            }
        }
        
        [DbColumn(Name="Floor", TypeName="int", IsPrimaryKey=true, Length=4)]
        public virtual int Floor
        {
            get
            {
                return this._Floor;
            }
            set
            {
                this._Floor = value;
            }
        }
        
        [DbColumn(Name="SequenceNo", TypeName="int", IsPrimaryKey=true, Length=4)]
        public virtual int SequenceNo
        {
            get
            {
                return this._SequenceNo;
            }
            set
            {
                this._SequenceNo = value;
            }
        }
        
        [DbColumn(Name="ProductCode", TypeName="varchar", Nullable=true, Length=7)]
        public virtual string ProductCode
        {
            get
            {
                return this._ProductCode;
            }
            set
            {
                this._ProductCode = value;
            }
        }
        
        [DbColumn(Name="Quantity", TypeName="numeric", Nullable=true, DecimalPlace=4, Length=5)]
        public virtual System.Nullable<decimal> Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this._Quantity = value;
            }
        }
        
        [DbColumn(Name="SupplierLocality", TypeName="int", Length=4, Remarks="1：HRD 2：日本")]
        public virtual int SupplierLocality
        {
            get
            {
                return this._SupplierLocality;
            }
            set
            {
                this._SupplierLocality = value;
            }
        }
        
        [DbColumn(Name="WoodKindCode", TypeName="int", Nullable=true, Length=4)]
        public virtual System.Nullable<int> WoodKindCode
        {
            get
            {
                return this._WoodKindCode;
            }
            set
            {
                this._WoodKindCode = value;
            }
        }
        
        [DbColumn(Name="SizeName", TypeName="varchar", Nullable=true, Length=30)]
        public virtual string SizeName
        {
            get
            {
                return this._SizeName;
            }
            set
            {
                this._SizeName = value;
            }
        }
        
        [DbColumn(Name="UsedPreservativeTreatment", TypeName="bit", Length=1, Remarks="1：防腐あり")]
        public virtual bool UsedPreservativeTreatment
        {
            get
            {
                return this._UsedPreservativeTreatment;
            }
            set
            {
                this._UsedPreservativeTreatment = value;
            }
        }
        
        [DbColumn(Name="StartedProductionDate", TypeName="datetime", Nullable=true, DecimalPlace=3, Length=8)]
        public virtual System.Nullable<System.DateTime> StartedProductionDate
        {
            get
            {
                return this._StartedProductionDate;
            }
            set
            {
                this._StartedProductionDate = value;
            }
        }
        
        [DbColumn(Name="FinishedProcessDate", TypeName="datetime", Nullable=true, DecimalPlace=3, Length=8)]
        public virtual System.Nullable<System.DateTime> FinishedProcessDate
        {
            get
            {
                return this._FinishedProcessDate;
            }
            set
            {
                this._FinishedProcessDate = value;
            }
        }
        
        [DbColumn(Name="FinishedPreservativeTreatmentDate", TypeName="datetime", Nullable=true, DecimalPlace=3, Length=8)]
        public virtual System.Nullable<System.DateTime> FinishedPreservativeTreatmentDate
        {
            get
            {
                return this._FinishedPreservativeTreatmentDate;
            }
            set
            {
                this._FinishedPreservativeTreatmentDate = value;
            }
        }
        
        [DbColumn(Name="Package", TypeName="int", Length=4)]
        public virtual int Package
        {
            get
            {
                return this._Package;
            }
            set
            {
                this._Package = value;
            }
        }
        
        [DbColumn(Name="ShippingWarehouseCode", TypeName="varchar", Nullable=true, Length=3)]
        public virtual string ShippingWarehouseCode
        {
            get
            {
                return this._ShippingWarehouseCode;
            }
            set
            {
                this._ShippingWarehouseCode = value;
            }
        }
        
        [DbColumn(Name="Remarks", TypeName="nvarchar", Nullable=true, Length=200)]
        public virtual string Remarks
        {
            get
            {
                return this._Remarks;
            }
            set
            {
                this._Remarks = value;
            }
        }
        
        [DbColumn(Name="Uneditable", TypeName="bit", Length=1, Remarks="1：不可")]
        public virtual bool Uneditable
        {
            get
            {
                return this._Uneditable;
            }
            set
            {
                this._Uneditable = value;
            }
        }
        
        [DbColumn(Name="UpdatedDate", TypeName="datetime", Nullable=true, DecimalPlace=3, Length=8)]
        public virtual System.Nullable<System.DateTime> UpdatedDate
        {
            get
            {
                return this._UpdatedDate;
            }
            set
            {
                this._UpdatedDate = value;
            }
        }
        
        public static HouseConstructionMaterial Get(string _ConstructionCode, string _ConstructionMaterialCode, int _ConstructionMaterialDetailCode, int _Floor, int _SequenceNo)
        {
            HouseConstructionMaterial entity = new HouseConstructionMaterial();
            entity.ConstructionCode = _ConstructionCode;
            entity.ConstructionMaterialCode = _ConstructionMaterialCode;
            entity.ConstructionMaterialDetailCode = _ConstructionMaterialDetailCode;
            entity.Floor = _Floor;
            entity.SequenceNo = _SequenceNo;
            if (!entity.Fill())
            {
                return null;
            }
            return entity;
        }
    }
}
