//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.8762
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketPlan.WebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KSBU-AP;Initial Catalog=UnitWiring;Persist Security Info=True;User ID" +
            "=sa;Password=81at84;Connection Timeout=600")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KSBU-AP;Initial Catalog=HRDInformationService;Persist Security Info=T" +
            "rue;User ID=sa;Password=81at84;Connection Timeout=600")]
        public string ConnectionStringOfHRDInformationService {
            get {
                return ((string)(this["ConnectionStringOfHRDInformationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KSBU-AP;Initial Catalog=SiyoDataBroker;Persist Security Info=True;Use" +
            "r ID=sa;Password=81at84;Connection Timeout=600")]
        public string ConnectionStringOfSiyoDataBroker {
            get {
                return ((string)(this["ConnectionStringOfSiyoDataBroker"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KSBU-AP;Initial Catalog=SekisanDataBroker;Persist Security Info=True;" +
            "User ID=sa;Password=81at84;Connection Timeout=600")]
        public string ConnectionStringOfSekisanDataBroker {
            get {
                return ((string)(this["ConnectionStringOfSekisanDataBroker"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Sy_sv1\\Mgap\\Hrd\\SekisanDataBroker\\SendSekisanDatas.exe")]
        public string SendSekisanDatasExe {
            get {
                return ((string)(this["SendSekisanDatasExe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KSBU-AP;Initial Catalog=HRDInformationService4;Persist Security Info=" +
            "True;User ID=sa;Password=81at84;Connection Timeout=600")]
        public string ConnectionStringOfHRDInformationService4 {
            get {
                return ((string)(this["ConnectionStringOfHRDInformationService4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ksk-remote-sv\\\\administrator")]
        public string ExportDirectoryUserName {
            get {
                return ((string)(this["ExportDirectoryUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hrd2011!")]
        public string ExportDirectoryPassword {
            get {
                return ((string)(this["ExportDirectoryPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KSBU-AP;Initial Catalog=HemsMaterialInformations;Persist Security Inf" +
            "o=True;User ID=sa;Password=81at84;Connection Timeout=600")]
        public string ConnectionStringOfHemsMaterialInformations {
            get {
                return ((string)(this["ConnectionStringOfHemsMaterialInformations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Denki-svr2\\RimokonNiche\\")]
        public string RimokonNicheReportDirectory {
            get {
                return ((string)(this["RimokonNicheReportDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\wwwroot\\CHOPPER2013\\RimokonNichePatterns\\")]
        public string RimokonNichePatternImagePath {
            get {
                return ((string)(this["RimokonNichePatternImagePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Denki-svr2\\DipSwitch\\")]
        public string DipSwitchReportExportDirectory {
            get {
                return ((string)(this["DipSwitchReportExportDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Denki-svr2\\SpecialCircuitList\\")]
        public string SpecialCircuitListExportDirectory {
            get {
                return ((string)(this["SpecialCircuitListExportDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\wwwroot\\CHOPPER\\EleConImages\\On.jpg")]
        public string ElectricControlImage_Ari {
            get {
                return ((string)(this["ElectricControlImage_Ari"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\wwwroot\\CHOPPER\\EleConImages\\Off.jpg")]
        public string ElectricControlImage_Nashi {
            get {
                return ((string)(this["ElectricControlImage_Nashi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\wwwroot\\CHOPPER\\PowConNumImages\\")]
        public string PowerConditionerNumberImageFolderPath {
            get {
                return ((string)(this["PowerConditionerNumberImageFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KSBU-AP;Initial Catalog=Photovoltaic;Persist Security Info=True;User " +
            "ID=sa;Password=81at84;Connection Timeout=600")]
        public string ConnectionStringOfPhotovoltaic {
            get {
                return ((string)(this["ConnectionStringOfPhotovoltaic"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2016-09-01")]
        public global::System.DateTime StandardItemSwitchingDate {
            get {
                return ((global::System.DateTime)(this["StandardItemSwitchingDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\pdf\\")]
        public string XGWSettingReortExportDirectory {
            get {
                return ((string)(this["XGWSettingReortExportDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/NissanWebService/NissanWebService.asmx")]
        public string NissanServiceUrl {
            get {
                return ((string)(this["NissanServiceUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KSBU-AP;Initial Catalog=HtiKibiroi;Persist Security Info=True;User ID" +
            "=sa;Password=81at84;Connection Timeout=600")]
        public string ConnectionStringOfHtiKibiroi {
            get {
                return ((string)(this["ConnectionStringOfHtiKibiroi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Administrator")]
        public string NissanServiceUserName {
            get {
                return ((string)(this["NissanServiceUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("system")]
        public string NissanServicePassword {
            get {
                return ((string)(this["NissanServicePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KSBU-AP;Initial Catalog=FlagSetting;Persist Security Info=True;User I" +
            "D=sa;Password=81at84;Connection Timeout=600")]
        public string ConnectionStringOfFlagSetting {
            get {
                return ((string)(this["ConnectionStringOfFlagSetting"]));
            }
        }
    }
}
