//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.9151
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketPlan.WinUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\UnitWiring\\")]
        public string SystemDirectory {
            get {
                return ((string)(this["SystemDirectory"]));
            }
            set {
                this["SystemDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\UnitWiring\\Blocks\\")]
        public string BlockDirectory {
            get {
                return ((string)(this["BlockDirectory"]));
            }
            set {
                this["BlockDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\UnitWiring\\Drawings\\")]
        public string DrawingDirectory {
            get {
                return ((string)(this["DrawingDirectory"]));
            }
            set {
                this["DrawingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\UnitWiring\\Images\\")]
        public string ImageDirectory {
            get {
                return ((string)(this["ImageDirectory"]));
            }
            set {
                this["ImageDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\UnitWiring\\SystemBlocks\\")]
        public string SystemBlockDirectory {
            get {
                return ((string)(this["SystemBlockDirectory"]));
            }
            set {
                this["SystemBlockDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("denki_517@denki.hrd-s.com")]
        public string ServerUserName {
            get {
                return ((string)(this["ServerUserName"]));
            }
            set {
                this["ServerUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sc1dv")]
        public string ServerPassword {
            get {
                return ((string)(this["ServerPassword"]));
            }
            set {
                this["ServerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ksbu-share\\【1G共通書類】\\Projects\\CHOPPER\\仮想Denki-svr\\マスタ\\UnitWiring\\")]
        public string ServerSystemDirectory_Debug {
            get {
                return ((string)(this["ServerSystemDirectory_Debug"]));
            }
            set {
                this["ServerSystemDirectory_Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Denki-svr\\SYSTEM\\UnitWiring\\")]
        public string ServerSystemDirectory_Release {
            get {
                return ((string)(this["ServerSystemDirectory_Release"]));
            }
            set {
                this["ServerSystemDirectory_Release"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\\Ksbu-ora11\【1g共通書類】\Projects\CHOPPER\仮想Denki-svr\UNIT WIRING DXF DATA\</string>
  <string>\\Ksbu-ora11\【1g共通書類】\Projects\CHOPPER\仮想Denki-svr\Section Files\PDR\</string>
  <string>\\Ksbu-ora11\【1g共通書類】\Projects\CHOPPER\仮想Denki-svr\Section Files\SHINSEI\</string>
  <string>\\Ksbu-ora11\【1g共通書類】\Projects\CHOPPER\仮想Denki-svr\Section Files\UNIT WIRING\</string>
  <string>\\Ksbu-ora11\【1g共通書類】\Projects\CHOPPER\仮想Denki-svr\Section Files\FBW\</string>
  <string>\\Ksbu-ora11\【1g共通書類】\Projects\CHOPPER\仮想Denki-svr\Section Files\SUJIKAI\</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServerDrawingDirectories_Debug {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServerDrawingDirectories_Debug"]));
            }
            set {
                this["ServerDrawingDirectories_Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\\Denki-svr\Section Files\UNIT WIRING DXF DATA\</string>
  <string>\\Denki-svr\Denkidata\AUTOCAD FILES\PDR\</string>
  <string>\\Denki-svr\Denkidata\AUTOCAD FILES\FBW\</string>
  <string>\\Denki-svr\Denkidata\AUTOCAD FILES\SUJIKAI\</string>
  <string>\\Denki-svr\Denkidata\AUTOCAD FILES\SICKHOUSE\</string>
  <string>\\Denki-svr\Denkidata\AUTOCAD FILES\BRANCH\</string>
  <string>\\Denki-svr\Denkidata\AUTOCAD FILES\GC\</string>
  <string>\\Denki-svr\Denkidata\AUTOCAD FILES\HENKOU\</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServerDrawingDirectories_Release {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServerDrawingDirectories_Release"]));
            }
            set {
                this["ServerDrawingDirectories_Release"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>HPD</string>
  <string>HSH</string>
  <string>HUW</string>
  <string>HSA</string>
  <string>HJA</string>
  <string>HHY</string>
  <string>HZA</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DrawingPrefixes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DrawingPrefixes"]));
            }
            set {
                this["DrawingPrefixes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\UnitWiring_CSV\\")]
        public string LightSerialCsvExportDirectory_Debug {
            get {
                return ((string)(this["LightSerialCsvExportDirectory_Debug"]));
            }
            set {
                this["LightSerialCsvExportDirectory_Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Sy_sv1\\UnitWiring_CSV\\")]
        public string LightSerialCsvExportDirectory_Release {
            get {
                return ((string)(this["LightSerialCsvExportDirectory_Release"]));
            }
            set {
                this["LightSerialCsvExportDirectory_Release"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\UnitWiringTest\\Exported\\")]
        public string ExportedCSVPath {
            get {
                return ((string)(this["ExportedCSVPath"]));
            }
            set {
                this["ExportedCSVPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hrdapps66/CHOPPER2013PS5/SocketPlanMasterMaintenance/SocketPlanMasterMaint" +
            "enance.application")]
        public string MasterMaintenanceUrl {
            get {
                return ((string)(this["MasterMaintenanceUrl"]));
            }
            set {
                this["MasterMaintenanceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\UnitWiring\\")]
        public string LocalSystemDirectory {
            get {
                return ((string)(this["LocalSystemDirectory"]));
            }
            set {
                this["LocalSystemDirectory"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hrdapps22/SocketPlan/SocketPlanService.asmx")]
        public string SocketPlan_WinUI_SocketPlanServiceReference_SocketPlanService {
            get {
                return ((string)(this["SocketPlan_WinUI_SocketPlanServiceReference_SocketPlanService"]));
            }
        }
    }
}
